- hosts: node1, node3
  tasks:
    - archive:
        path: /var/log
        dest: /var/www/html/group1.tar.gz
      tags: nogroup1

- hosts: node2, node4
  tasks:
    - archive:
        path: /var/www/html
        dest: /var/www/html/group2.tar.gz
      tags: nogroup2
